---

- name: Ensure /etc/docker directory exists
  file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: set docker mtu
  copy:
    content: '{"mtu": 1442}'
    dest: /etc/docker/daemon.json

- name: install packages
  apt:
    name:
      - docker.io
    update_cache: yes
